#!/bin/bash
if [ $(id -u) -eq 0 ]
then
        clear
else
        if echo $(id) |grep sudo > /dev/null
        then
        clear
        echo "Voce não é root"
        echo "Seu usuario esta no grupo sudo"
        echo -e "Para virar root execute \033[1;31msudo su\033[0m"
        exit
        else
        clear
        echo -e "Vc nao esta como usuario root, nem com seus direitos (sudo)\nPara virar root execute \033[1;31msu\033[0m e digite sua senha root"
        exit
        fi
fi
clear
echo -e "\033[1;37m VpsPacket © Script criado por: \033[2;32mMatheus Larcher \033[0m"
echo -e "\033[1;37mEscolha uma das opçoẽs:    \033[1;37mPara Sair Ctrl + C\033[1;34m
[1] On \033[2;36m(Ligar o servidor)\033[1;34m
[2] server_config \033[2;36m(Abrir o arquivo de Configuração do servidor)\033[1;34m
[3] ssh_config \033[2;36m(Instalar e configurar servidor)\033[0m"
read -p "[1-3]: " opcao
case $opcao in
 1)
  bash On
  read -n1 -r -p " Pressione uma tecla para Abrir novamente o config..."
  bash config;;
 2)
  bash server_config
  read -n1 -r -p " Pressione uma tecla para Abrir novamente o config..."
  bash config;;
 3)
  bash ssh_config
  read -n1 -r -p " Pressione uma tecla para Abrir novamente o config..."
  bash config;;
   *)
  id > /dev/null 2> /dev/null
esac
